// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJPGjeZLWt42mhP3Jj21_QHWr2IYXHR_4',
    appId: '1:827950512534:web:efe15dfd171b7efa6845b7',
    messagingSenderId: '827950512534',
    projectId: 'debtmate-311dd',
    authDomain: 'debtmate-311dd.firebaseapp.com',
    storageBucket: 'debtmate-311dd.firebasestorage.app',
    measurementId: 'G-0JGRJ0TBBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIVuTaX_H1n6tdlVYC3n9qGXj-OztogAY',
    appId: '1:827950512534:android:9c93497488c669ce6845b7',
    messagingSenderId: '827950512534',
    projectId: 'debtmate-311dd',
    storageBucket: 'debtmate-311dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbrxCyc-Rpc9SaqaYRriMvdNLdzSpGlz0',
    appId: '1:827950512534:ios:ede331db12f1d9196845b7',
    messagingSenderId: '827950512534',
    projectId: 'debtmate-311dd',
    storageBucket: 'debtmate-311dd.firebasestorage.app',
    iosBundleId: 'com.example.debtmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbrxCyc-Rpc9SaqaYRriMvdNLdzSpGlz0',
    appId: '1:827950512534:ios:ede331db12f1d9196845b7',
    messagingSenderId: '827950512534',
    projectId: 'debtmate-311dd',
    storageBucket: 'debtmate-311dd.firebasestorage.app',
    iosBundleId: 'com.example.debtmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJPGjeZLWt42mhP3Jj21_QHWr2IYXHR_4',
    appId: '1:827950512534:web:94b884b951aee8be6845b7',
    messagingSenderId: '827950512534',
    projectId: 'debtmate-311dd',
    authDomain: 'debtmate-311dd.firebaseapp.com',
    storageBucket: 'debtmate-311dd.firebasestorage.app',
    measurementId: 'G-QRBKS7HLK5',
  );

}